global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using SOLID1.SingleResponsibility;
global using SOLID1.OpenClosed;
global using SOLID1.LiskovSubstitution;
global using SOLID1.InterfaceSegragation;
//global using SOLID1.DependencyInversion;
global using Calendar = SOLID1.LiskovSubstitution.Calendar;